<a href="https://colab.research.google.com/github/Shankjbs571/DataAnalytics/blob/main/BusinessAnalyticsWeek7.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import statsmodels.formula.api as smf
import numpy as np

data = {
    'Sales': [53, 12, 15, 27, 8, 12, 27, 17, 61, 20, 95, 33, 19, 15, 43, 11, 20, 36, 7, 9,
              21, 25, 29, 18, 6, 7, 15, 23, 51, 93, 51, 14, 41, 8, 114, 35, 18, 9, 46, 17,
              43, 63, 8, 34, 145, 18, 40, 17, 17, 12],
    'Price': [1, 3.4, 3.3, 1.4, 3.7, 3.6, 2.2, 1.7, 1.4, 3.2, 0.8, 1.1, 2.5, 3.3, 1, 2.6, 3,
              2.4, 3.6, 2.8, 2.4, 2.3, 2.1, 1.8, 3.6, 3.7, 2.9, 1.2, 1.1, 1.2, 1, 3.7, 1.2,
              3.4, 1, 2.5, 2, 3.3, 1.8, 2, 1.3, 0.8, 3.6, 1.6, 0.9, 2.4, 1.7, 2.8, 3.2, 3.7]
}

df = pd.DataFrame(data)

model = smf.ols('Sales ~ Price', data=df).fit()

r_squared = model.rsquared

print(f'R-squared value: {r_squared:.2f}')

R-squared value: 0.53

In [ ]:
print(model.summary())

                            OLS Regression Results
==============================================================================
Dep. Variable:                  Sales   R-squared:                       0.526
Model:                            OLS   Adj. R-squared:                  0.516
Method:                 Least Squares   F-statistic:                     53.34
Date:                Sun, 11 Aug 2024   Prob (F-statistic):           2.52e-09
Time:                        08:09:47   Log-Likelihood:                -219.72
No. Observations:                  50   AIC:                             443.4
Df Residuals:                      48   BIC:                             447.3
Df Model:                           1
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
Intercept     79.9927      7.209     11.095      0.000      65.497      94.488
Price        -21.2052      2.903     -7.304      0.000     -27.043     -15.368
==============================================================================
Omnibus:                       35.987   Durbin-Watson:                   2.229
Prob(Omnibus):                  0.000   Jarque-Bera (JB):              104.127
Skew:                           1.955   Prob(JB):                     2.45e-23
Kurtosis:                       8.890   Cond. No.                         7.22
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.

In [ ]:

df['log_Sales'] = np.log(df['Sales'])
df['log_Price'] = np.log(df['Price'])

model_log = smf.ols('log_Sales ~ log_Price', data=df).fit()

print(model_log.summary())

r_squared_log = model_log.rsquared
print(f"R-squared value on the transformed dataset: {r_squared_log:.2f}")

                            OLS Regression Results
==============================================================================
Dep. Variable:              log_Sales   R-squared:                       0.760
Model:                            OLS   Adj. R-squared:                  0.755
Method:                 Least Squares   F-statistic:                     152.0
Date:                Sun, 11 Aug 2024   Prob (F-statistic):           1.74e-16
Time:                        16:13:42   Log-Likelihood:                -22.079
No. Observations:                  50   AIC:                             48.16
Df Residuals:                      48   BIC:                             51.98
Df Model:                           1
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
Intercept      4.1333      0.097     42.560      0.000       3.938       4.329
log_Price     -1.3814      0.112    -12.329      0.000      -1.607      -1.156
==============================================================================
Omnibus:                        4.492   Durbin-Watson:                   1.989
Prob(Omnibus):                  0.106   Jarque-Bera (JB):                2.018
Skew:                           0.127   Prob(JB):                        0.365
Kurtosis:                       2.049   Cond. No.                         3.31
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
R-squared value on the transformed dataset: 0.76

In [ ]:
import io
import pandas as pd
X = pd.read_csv(io.StringIO('''
175349.2,116897.8,491784.1,0,1
172597.7,131377.59,463898.53,0,0
163441.51,81145.55,427934.54,1,0
154372.41,98671.85,403199.62,0,1
152107.34,71391.77,386168.42,1,0
141876.9,79814.71,382861.36,0,1
144615.46,127198.87,147716.82,0,0
140298.13,125530.06,343876.68,1,0
130542.52,128718.95,331613.29,0,1
133334.88,88679.17,324981.62,0,0
111913.08,90594.11,249160.95,1,0
110671.96,71790.61,269744.55,0,0
103863.75,107320.38,269839.44,1,0
101992.39,115495.07,272664.93,0,0
129943.24,136547.42,276512.92,1,0
124523.61,102616.84,281776.23,0,1
88013.11,101597.55,284346.06,0,0
104657.16,125077.58,302574.31,0,1
101749.16,94175.79,314919.57,1,0
96419.7,133514.11,20000,0,1
86253.86,93867.3,318664.47,0,0
88389.47,133773.43,319737.29,0,1
83994.56,102782.75,323319.26,1,0
77532.53,85751.03,324768.73,1,0
87044.01,79281.34,160574.81,0,1
74664.71,119553.16,157962.62,0,0
85328.87,124135.98,154050.07,1,0
82107.6,107864.55,373183.81,0,1
76051.52,162645.56,138148.2,1,0
75605.48,133032.06,127138.38,0,1
71994.48,95641.28,111131.24,1,0
71136.38,132701.92,108218.23,0,1
73408.86,109219.61,66085.25,0,0
65493.95,83057.49,234634.81,1,0
56426.07,137693.92,230797.67,0,0
56014.02,65047.44,225517.64,0,1
38663.76,107056.21,221126.82,1,0
54069.95,31283.14,217029.42,0,0
30229.59,45947.93,205265.1,0,1
48558.51,62982.09,194999.3,0,0
38754.33,98546.05,192795.67,0,0
37892.92,64710.77,184470.71,1,0
33640.93,76189.63,168001.11,0,0
25505.73,107382.3,55534.17,0,1
32177.74,134806.14,48334.72,0,0
11000.23,104153.04,21903.93,0,1
11315.46,95816.21,317114.46,1,0
10000,115426.92,20000,0,0
10542.05,31743.15,20000,0,1
10000,96983.8,65173.06,0,0
'''), header=None)

Y = pd.read_csv(io.StringIO('''
227261.83
226792.06
226050.39
217901.99
201187.94
191991.12
191122.51
190752.6
187211.77
184759.96
181121.95
179259.4
176585.52
169307.35
167602.65
164917.04
161992.93
160370.37
159266.9
157776.86
153474.03
146313.02
145352.25
143733.99
143552.04
142404.34
140733.54
140008.31
138282.38
136004.64
134937.59
132483.56
132427.84
131778.92
131712.8
131479.51
125708.19
124949.14
116229.06
116005.76
113239.91
112798.83
106498.49
104758.98
100200.33
99926.08
84490.75
77559.73
70673.41
49681.4
'''), header=None)

In [ ]:
Y

            0
0      Profit
1   227261.83
2   226792.06
3   226050.39
4   217901.99
5   201187.94
6   191991.12
7   191122.51
8    190752.6
9   187211.77
10  184759.96
11  181121.95
12   179259.4
13  176585.52
14  169307.35
15  167602.65
16  164917.04
17  161992.93
18  160370.37
19   159266.9
20  157776.86
21  153474.03
22  146313.02
23  145352.25
24  143733.99
25  143552.04
26  142404.34
27  140733.54
28  140008.31
29  138282.38
30  136004.64
31  134937.59
32  132483.56
33  132427.84
34  131778.92
35   131712.8
36  131479.51
37  125708.19
38  124949.14
39  116229.06
40  116005.76
41  113239.91
42  112798.83
43  106498.49
44  104758.98
45  100200.33
46   99926.08
47   84490.75
48   77559.73
49   70673.41
50    49681.4

In [ ]:
# Step 1: Import necessary libraries
# import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score

# Step 2: Load the data from the provided Excel files
# X = pd.read_excel("X.xlsx")
# y = pd.read_excel("y.xlsx")

# Step 3: Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size=0.2, random_state=0)

# Step 4: Initialize the linear regression model
model = LinearRegression()

# Step 5: Fit the model on the training data
model.fit(X_train, y_train)

# Step 6: Predict the target variable for the test data
y_pred = model.predict(X_test)

# Step 7: Calculate the R-squared value
r2 = r2_score(y_test, y_pred)
print(f"R-squared value of the model: {r2}")

R-squared value of the model: 0.9347068473282425

In [ ]:
intercept = model.intercept_
print(f"Intercept of the model: {intercept}")

Intercept of the model: [69744.98712385]

In [ ]:
X_new = [[1315.46, 115816.21, 297114.46, 1, 0]]

# Step 7: Predict the profit using the model
predicted_profit = model.predict(X_new)
print(f"Predicted Profit: {predicted_profit[0]}")

Predicted Profit: [84489.1056363]